runtime: php55
api_version: 1
threadsafe: true

handlers:
###################################################

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt
  secure: always

- url: /favicon.ico
  static_files: public/i/favicon.ico
  upload: public/i/favicon.ico
  secure: always

- url: /(.*\.(gif|png|jpg))$
  static_files: public/\1
  upload: public/.*\.(gif|png|jpg)$
  secure: always

- url: /c
  static_dir: public/c
  secure: always

- url: /j
  static_dir: public/j
  secure: always

- url: /i
  static_dir: public/i
  secure: always

- url: /d
  static_dir: public/d
  secure: always

- url: /tutorial/hw2/RDN_Document
  static_dir: public/tutorial/hw2/RDN_Document
  secure: always

####################################################

- url: /
  script: public/index.php
  secure: always

- url: /link/.*\.html?
  script: public/link/all.php
  secure: always

- url: (/(download/.*|game/.*|info/.*|link/.*|mod/.*|tutorial/.*)?[a-z_]*).html?
  script: public\1.php
  secure: always

- url: /.*
  script: error/404.php
  secure: always

###################################################

error_handlers:
- file: error/default.html

# - error_code: over_quota
#   file: error/over_quota.html

# - error_code: dos_api_denial
#   file: error/over_quota.html
