runtime: php81

handlers:
###################################################

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt

- url: /favicon.ico
  static_files: public/i/favicon.ico
  upload: public/i/favicon.ico

- url: /(.*\.(gif|png|jpg|svg))$
  static_files: public/\1
  upload: public/.*\.(gif|png|jpg|svg)$

- url: /c
  static_dir: public/c

- url: /j
  static_dir: public/j

- url: /i
  static_dir: public/i

- url: /d
  static_dir: public/d

- url: /tutorial/hw2/RDN_Document
  static_dir: public/tutorial/hw2/RDN_Document

####################################################

- url: /.*
  script: auto
  redirect_http_response_code: 301

###################################################

error_handlers:
- file: error/default.html

# - error_code: over_quota
#   file: error/over_quota.html

# - error_code: dos_api_denial
#   file: error/over_quota.html

###################################################

automatic_scaling:
  max_instances: 1
